groups:
  Company:
  - company_careers
  Experimental:
  - google_jobs
  - wellfound
  Global:
  - remoteok
  - weworkremotely
  - remotive
  - arbeitnow
  India:
  - naukri
  - foundit
  - instahyre
